- name: 'Copiando docker-compose do Jenkins'
  copy:
    src: files/docker-compose.yml
    dest: /home/vagrant/docker-compose.yml
  become: yes

- name: 'Subdindo docker-compose'
  shell: docker-compose up -d
  become: yes
