---
- name: 'Removendo versoes antigas do docker'
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
  become: yes

- name: 'Adicionar chave do repositorio Docker'
  warn: false
  shell:  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: 'Adicionar repositório docker estável'
  shell:  echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: 'Instalando o Docker'
  apt:
    update_cache: yes
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
  become: yes 
